### ISSUE TITLE
Progress bar stays on 0%

### ISSUE THREAD

**Issue by sametmax** [tqdm/tqdm#113]
Using Python 3.5 on Ubuntu 14.04 64b with the native OS terminal and vanilla Python shell:

    >>> for i in tqdm(range(9)):
    ...     print('test')
    ... 
      0%|                                                                                                                   | 0/9 [00:00<?, ?it/s]test
    test
    test
    test
    test
    test
    test
    test
    test
    >>> tqdm.__version__
    '3.7.1'

The bar stays in that state:

    0%|                                                                                                                   | 0/9 [00:00<?, ?it/s]

**Comment by casperdcl** [comment]
The bar would've been cleared if you hadn't been printing to console in the loop.

**Comment by casperdcl** [comment]
This would work:

```python

>>> output = []
>>> for i in trange(9):
...     output.append(str(i))
>>>
>>> print '\n'.join(output)

```

**Comment by casperdcl** [comment]
If you want to force the bar to update more than the default max of 10 times per second you'll need `mininterval=0` or `miniters=1` etc. You could also have `leave=True` to simply force an update at the end.

**Comment by sametmax** [comment]
No your solution actually doesn't print any bar at all:

    >>> from tqdm import tqdm
    >>> output = []
    >>> for i in tqdm(range(9)):
    ...      output.append(str(i))
    ... 
    >>> print('\n'.join(output))                                                                                                                  
    0
    1
    2
    3
    4
    5
    6
    7
    8

**Comment by sametmax** [comment]
Ok, got it. Thanks.

But be careful, the doc gives you this example:

https://github.com/tqdm/tqdm#iterable-based

And according to what you are saying, it doesn't work.

**Comment by casperdcl** [comment]
Thanks, good spot. You're rightm it shouldn't have a print statement in the loop (unless the output of tqdm was redirected to a different place)

**Comment by casperdcl** [comment]
Thanks, good spot. You're right it shouldn't have a print statement in the loop (unless the output of tqdm was redirected to a different place)

**Comment by sametmax** [comment]
And shouldn't update() force draw the bar?

Because:

    >>> with tqdm(total=100) as pbar:                                                                                                             
    ...     for i in range(10):
    ...         pbar.update(10)
    ... 

Does nothing, which is strange since I'm requesting the update manually, so this mean I want it to happen no matter the minstuff params. Or at least put an update(force_draw) which default to True to help new comers.

And write in big in the doc "Do not print" :) Or wrap print, or provide an alternative to print. Something so that you can write during the progress bar, because you don't always have control of whose printing, and having to capture stding manually everytime would be a pain.

**Comment by lrq3000** [comment]
Casper is correct, you can use your original example as long as you set
mininterval=0 and miniter=1.

This is a feature not a bug, even if it can be counterintuitive in some
simple examples like yours (it happens to me too once in a while to scratch
my head for a minute wondering why there's no tqdm output, before
remembering that tqdm skips useless iterations by default to minimize
overhead).

Please try your original example but with the two parameters above, this
shoumd fix your issue.

**Comment by sametmax** [comment]
@casperdcl lrq3000: I removed that comment 1 seconde after writting it :) I realized how stupid I was.

@casperdcl: I would do it this way:

1 - wraps stdin by default
2 - if someone tries to write to stdin, throws and exception explaining you should either not do it, or specify what you want.
3 - provide a configuration option saying stdin_policy='error|buffer|silence|nowrap'

It would do:

- error: default value. Raises an error with a helpful message saying what you have to do. It makes sense because it render tqdm useless if you don't take decision.
- buffer: the wrapper buffer anything written, and and the end you can just print the buffer.
- silence: just do not print anything.
- do not wrap stdin, so people can decide what to do manually and avoid magic.

Should I open another ticket for that ?

**Comment by casperdcl** [comment]
We could have `leave=True` by default. We cannot have force update by default as this is equivalent to miniters=0 by default, and tqdm is all about optimisation by default.

**Comment by sametmax** [comment]
Makes sense. Thanks you for being so helpful.

**Comment by casperdcl** [comment]
@samtemax we alteady have that. What you mean is `tqdm(..., file=sys.stderr, ...)`. We cannot check whether stderr is the same as stdout or that you're writing to either. That's not tqdm's job...

**Comment by sametmax** [comment]
No I what I meant is not how to write on stderr, but how to make sure people don't print mistakenly while using the bar. 

This solution provides:

- an explicit error when something tries to print without explicitly choosing a solution to the problem;
- tools for comon work around.

Also, you may to update examples such as https://github.com/tqdm/tqdm#manual to include miniter in it otherwise copying/pasting from the doc leads to no toolbar and it if you don't know what's going on it feels like it doesn't work.

**Comment by lrq3000** [comment]
Sorry sametsam, i have only access to github through my mails currently so
I won't see any edit and ill have some delay :S

About forcing the printing of tqdm, we could have a new methode
tqdm.refresh() to do that, this should be easily feasible.

However about printing management, even if I am with you that this can be
problematic, it's not tqdm job to manage the printing of other messages.
First because the dev using tqdm should know better what fits for his case
(buffering,  logging, instant printing if info is urgent, etc), and
secondly because catching all printing by tqdm is bound to hardly fail and
produce big side effects.

The other solution you proposed, that tqdm provides its own print method to
print messages alongside the bar, is an idea that i could agree with but
technically this is awful, because we don't just provide one bar but nested
and even freely positioned bars. Managing messages for each bar becomes
quite quickly impossible and is bound to produce big weird display issues.

For all these reasons, and since I think we should focus on progress bar
management rather than messages handling, I think we should just leave it
at that. We'll eventually see later if it becomes a necessary feature to
implement.

**Comment by sametmax** [comment]
Ok.

**Comment by lrq3000** [comment]
But i'm still thinking about tqdm.print(). Maybe by using a class var to
store the messages,  and force refresh all bars,  we could cleanly print
messages and just move progress bars below. Something to ponder...

**Comment by lrq3000** [comment]
In addition, such a class method would be great to overwrite and customize
for subclasses. For example gui tqdm and ipython bar could rather print
messages in a dedicated scrollbar box below the progress bars.

**Comment by sametmax** [comment]
Better provide a tqdm logger with sane default then. This way you can configure it the way you want : buffer, scrollbar box, log file, and people can configure it using the logging module.

**Comment by lrq3000** [comment]
From what I understood with your original example, the goal of tqdm.print()
would be to print parent app messages, not log internal tqdm message.
That's the issue: the dev using tqdm cannot print while using tqdm. But he
can of course log wherever he wants to, tqdm does not prevent that (and
since it's outputting to stderr by default, someone logging stdout won't
log tqdm's output, I use this trick extensively in my own scripts).

About scrollbar boxes and other modalities, yes this will eventually be
implemented by subclasses.

2016-01-21 21:55 GMT+01:00 sametmax <notifications@github.com>:

**Comment by sametmax** [comment]
No, that's not what I mean.

I'm not talking about tqdm internals. What I meant was : instead of 
providing a tqdm.print(), provide a
custom logger. This way it integrates well with Python tools.
