### ISSUE TITLE
AttributeError: 'FloatProgress' object has no attribute 'style'

### ISSUE THREAD

**Issue by jvpeetz** [tqdm/tqdm#1156]
- [x] I have marked all applicable categories:
    + [x] exception-raising bug
    + [ ] visual output bug
    + [ ] documentation request (i.e. "X is missing from the documentation." If instead I want to ask "how to use X?" I understand [StackOverflow#tqdm] is more appropriate)
    + [ ] new feature request
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:
  ```python
  import tqdm, sys
  print(tqdm.__version__, sys.version, sys.platform)
  ```
4.57.0 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] linux

```
python3 -m pip list | grep -E '(jupy|noteb|widge)' 
```
ipywidgets               6.0.0
jupyter-client           6.1.11
jupyter-core             4.7.1
notebook                 6.2.0
widgetsnbextension       2.0.0

Hi,
trying this little example on Debian testing/sid in Jupyter:
```
from tqdm.notebook import trange, tqdm
from time import sleep

for i in trange(3, desc='1st loop'):
    for j in tqdm(range(100), desc='2nd loop'):
        sleep(0.01)
```
results in the exception
```
AttributeError: 'FloatProgress' object has no attribute 'style'
```
Therefore, I would suggest to change the lines
```
            return self.container.children[-2].style.bar_color
```
and
```
           self.container.children[-2].style.bar_color = bar_color
```
in file `tqdm/notebook.py` to
```
            return self.container.children[-2].bar_style
```
and
```
           self.container.children[-2].bar_style = bar_color
```
which would work with `ipywidget`'s `IntProgress` and `FloatProgress`.
What do you think?
Regards,
Jörg.

**Comment by jras** [comment]
Maybe, a problem in Debian is that the [package ipywidgets](https://tracker.debian.org/pkg/ipywidgets) is already in version 6.0.0, even in recent uploads and in unstable. There is, since 2018, a [request to package v.7 of ipywidgets](https://bugs.debian.org/896460) to solve some problems in other packages.

Instead of modifying the file `tqdm/notebook.py` in the system, we have solved the error in tqdm, by just installing an ipywidgets version more recent than 7.0 with pip in the system:
```
python3 -m pip install "ipywidgets>=7.0"
```
that currently installed ipywidgets-7.6.3, and also jupyterlab-widgets-1.0.0  and widgetsnbextension-3.5.1.

**Comment by jvpeetz** [comment]
Thanks for the information and the hints. That made me sent a [supporting message](https://bugs.debian.org/896460#34) to the request to package v.7 of ipywidgets. Therefore, I'm closing this issue.
Regards,
Jörg.
