### ISSUE TITLE
Reduce overhead automatically

### ISSUE THREAD

**Issue by casperdcl** [tqdm/tqdm#13]
The code below shows that for the simplest of generators, there's quite an overhead. This is to be expected as there's not much content in the loop itself.

The 6x increase isn't that bad (especially when compared to the de-facto `ProgressBar`, hah). However, this is reduced to about 3x if we set `miniters` to be high enough that it limits update more than the `mininterval`. This is due to the internal time updating of the function.

I think it's best to attempt to set a higher `miniters` by default (maybe based on iterator arguments, like `max(int(args[0] / 100), 1)`) or at least document this effect somewhere...

Still. 100x faster that `ProgressBar` in some scenarios. And prettier by default. Nice :+1: 

`xrange`: 3.02 sec
`tqdm.trange`: 19.6 sec
`tqdm.trange, miniters=niters/100`: 9.71 sec
`progressbar.ProgressBar()(xrange)`: 87.8 sec

```{python}
#!/usr/bin/env python2.7

# Profiling/overhead tests
from timeit import timeit


stmts = ('[i for i in xrange(int(1e8))]',
    'import tqdm; [i for i in tqdm.trange(int(1e8))]',
    'import tqdm; [i for i in tqdm.trange(int(1e8), miniters=int(1e6))]',
    'import progressbar; [i for i in progressbar.ProgressBar()(xrange(int(1e8)))]')
for s in stmts:
    print s
    print timeit(stmt=s, number=1), 'seconds'
```

**Comment by hadim** [comment]
Well I am in favour ok keeping things simple for the user who won't (in most of the case) bother tweaking parameters such as `miniters`, `mininterval`, and so forth...

So we should find the best default parameters working well for most user case.

`miniters=niters/100` seems fine to me but assuming that `niters == total`, this value is not always known and so we have to take this into account.

About your test performance I am not sure at which point is it relevant because inside the loop you do nothing (except storing the value i in a list. My bet would be that for expensive calculation the overhead will be dramatically reduced. However this is just an intuition and more tests are needed to confirm it.

**Comment by casperdcl** [comment]
When we say 'overhead' we usually refer to fraction of total time taken for the progressbar maintenance/update.

However, if we define overhead to mean simply the maintenance/update time taken per iteration, then this will be constant regardless of how complex the loop calculations are.

Basically my results show a progressbar overhead of:

- 166 ns per iteration for `trange`
- 67 ns per iteration for `trange` with a 'good' `miniters` value
- 848 ns per iteration for `progressbar.ProgressBar()(xrange)`

**Comment by hadim** [comment]
What kind of calcution do you propose for a "good `miniters`" ? Because I think it will mainly depend on the ratio (number of iterations) over (time taken for each iterations).

**Comment by casperdcl** [comment]
Yes that's what I was thinking... if `miniters` was not specified then when we update based on a `mininterval`, we should set a value for `miniters`.

**Comment by hadim** [comment]
+1

Feel free to open a PR, the discussion can continue there.

**Comment by casperdcl** [comment]
Lol just cracked it while chatting here. Gets even better than guessing a good `miniters` -- getting 55ns/iter.
