### ISSUE TITLE
Manual .update(0) updates by 1

### ISSUE THREAD

**Issue by mcdallas** [tqdm/tqdm#133]
I am not sure if this is on purpose but if you manually update by 0 it still updates the progress bar.
you can test it with
```sh
from tqdm import tqdm
from time import sleep
with tqdm(total=20) as pbar:
    for i in range(20):
        pbar.update(0)
        sleep(0.5)
```

**Comment by lrq3000** [comment]
Yes, this should update the progress bar but without increasing the number of done iterations.

This is because some third-party libraries, such as urllib, may feed `tqdm` with 0 when there's nothing new during one iteration. More info at #123.

I close the ticket, but if the bar doesn't stay at 0 with your example, feel free to reopen because this would be a bug.
