### ISSUE TITLE
Option to show an exponential rate trend

### ISSUE THREAD

**Issue by graingert** [tqdm/tqdm#140]
Exponentially increasing progress bars appear faster:

http://www.chrisharrison.net/projects/progressbars/ProgBarHarrison.pdf

it's probably a good idea to hide percentage calculations from these bars though.

**Comment by casperdcl** [comment]
Thanks for this. Having skimmed through the paper I think we already do better. `tqdm` uses an exponential weighted moving average which minimises overhead but allows some flexibility. Use the `smoothing` keyword argument if you need more control!

**Comment by graingert** [comment]
@casperdcl the smoothing docs aren't very clear on what it does.

**Comment by lrq3000** [comment]
@graingert What you propose is not really the same as what is implemented: we implement an exponential moving average algorithm to better predict the time it will take to complete the task by better adapting to hiccups and changes in speeds, but your proposition is to make an ergonomically designed progress bar that is pessimistic so that it speeds up towards the end, giving the user the feeling that the process gets faster and faster.

We already discussed about this solution in the past, but we didn't implement it (yet?). I don't think we will implement it in the near future, but if you want to give it a try, I have found a [few posts that could give a good start here](https://github.com/tqdm/tqdm/issues/48#issuecomment-154848125).

**Comment by lrq3000** [comment]
Actually, if we want to implement a pessimistic bar while still keeping the performance, I think we can make something out of just memorizing the slowest time and the fastest time per iteration, and we can just then apply this ratio on the time prediction given the number of iteration are left: the idea is that closer we are from the start, the more we will weight iterations that took a time closer to the slowest bound ; the closer from the end iteration, the more weight for iterations that are fast. This is pessimistic, and it requires only 2 new variables and 1 calculation.

**Comment by casperdcl** [comment]
I'm personally against making progress appear "faster" - I'd much prefer
accuracy and precision and spreading the love of this. Imagine someone
using `tqdm` as a benchmarking utility - this won't go down well. (Sorry,
I'm a scientist... I also prefer SI units to barbaric ones.)

**Comment by lrq3000** [comment]
@casperdcl agree, but the "ergonomic" feature could be an option we could disable. But yes, I agree that it's not a necessary one, I also prefer precision and benchmarking ability.
