### ISSUE TITLE
Option to ignore tqdm if number of iterations less than a specific threshold

### ISSUE THREAD

**Issue by ritviksahajpal** [tqdm/tqdm#165]
I have a function with a loop. This function can either be called with inputs which make it loop thousands of times or sometimes just 1 time.

Is there a way to specify that tqdm should show progress bar only if number of iterations exceeds a certain threshold?

**Comment by casperdcl** [comment]
use the optional keyword argument `disable`:

tqdm(..., disable=(total<10))

or similar.
On 16 May 2016 7:33 p.m., "Ritvik Sahajpal" <notifications@github.com>
wrote:

I have a function with a loop. This function can either be called with
inputs which make it loop thousands of times or sometimes just 1 time.

Is there a way to specify that tqdm should show progress bar only if number
of iterations exceeds a certain threshold?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/tqdm/tqdm/issues/165>

**Comment by ritviksahajpal** [comment]
thanks! this works.

**Comment by lrq3000** [comment]
So elegant :+1:
