### ISSUE TITLE
tqdm_notebook.write()?

### ISSUE THREAD

**Issue by mdering** [tqdm/tqdm#169]
Hi tqdm,
I'm trying to use this as a nicer wrapper for a machine learning library. Heres my code. This does not print anything, even though this method returns a 0 dimensional numpy array, which i convert to a scalar using asscalar. Can anyone help? Is this an issue. Using jupyter core 4.1.0

```
for epoch in tqdm_notebook(range(12)):
    for x,y in tqdm_notebook(data_gen(X_train,y_train),
                             total=X_train.shape[0]/16,leave=False,
                            desc = "epoch: {}".format(epoch)):
        loss = model.train_on_batch(x,y)
        losses.append(loss)
        tqdm_notebook.write("loss: {}".format(np.asscalar(loss)))
```

**Comment by casperdcl** [comment]
leave=False should clear any output once the loop is done. If the loop
itself completes quickly you probably won't notice any intermediate output
either.

doesn't sound like a bug. actually demonstrates that tqdm didn't add any
noticable overhead.

**Comment by lrq3000** [comment]
Ah you got me, I didn't implement `tqdm_notebook.write()`. I simply forgot because both features were initially on two different PRs, and I forgot to update `tqdm_notebook` when both got merged!

I will fix this in the next few days.

**Comment by casperdcl** [comment]
ah thanks Stephen

**Comment by lrq3000** [comment]
So I didn't implement `tqdm_notebook.write()` before because anyway `print()` works perfectly fine with `tqdm_notebook()` so there's no need for a replacement. But if you use both `tqdm_notebook` and `tqdm` in your application (if you intend it to be used both in IPython and in console), then I understand that a more standard way to print is needed.

I updated `tqdm_notebook` to provide the `write()` method, please try it in #171 and tell me if it works alright for your needs.
