### ISSUE TITLE
Calling script with nested bars in Jupyter Notebook

### ISSUE THREAD

**Issue by Jessime** [tqdm/tqdm#180]
Hi, I have a question about the proper way to handle this specific use case:

I have a script with nested progress bars. I'd like to be able to use that script both at the command-line on  a server that doesn't have jupyter, and also in the notebook. 

I can only get this to work properly on one at a time. I can use `tqdm()`, and run on the server, but the nested bars produce a mess of output in the notebook. Or, I can use `tqdm_notebook()`, which I believe was created at least partially to address the nested issues, and run my script perfectly in jupyter, but doesn't show any output for the command-line. 

Do I have to do something like:

```python
from tqdm import tqdm, tqdm_notebook
def loop(nb=False):
    if nb:
        bar = tqdm_notebook
    else:
        bar = tqdm
    return bar
```

I might just be missing something really obvious, but I couldn't find anything that addressed this in the documentation. Thanks!

**Comment by casperdcl** [comment]
assuming you have a global IS_NOTEBOOK:

```
if IS_NOTEBOOK:
    from tqdm import tqdm_notebook as tqdm
else:
    from tqdm import tqdm
```

then just use `tqdm` only in the rest of your code...

**Comment by Jessime** [comment]
Okay, great. Thanks again!

**Comment by lrq3000** [comment]
Casper gave the answer.

Just to clarify what `IS_NOTEBOOK` should be, it can either be :+1: 

* a variable you define as an argument of your script, so that users can explicitly tell your script whether it is run inside IPython or in the console (that's exactly what `tqdm` does, and it's the most reliable way).

* Or a check of environment inside your script to automagically adapt. This way is problematic because IPython's devs do not want IPython to provide the env, because of design (they want it to be environment agnostic since the project evolved to Jupyter), but you can maybe use:

```
IS_NOTEBOOK = False
try:
    IS_NOTEBOOK = True if get_ipython() else False
except NameError as exc:
    pass

However, be warned that this might change in the future. For more info, see this thread:
http://stackoverflow.com/questions/15411967/how-can-i-check-if-code-is-executed-in-the-ipython-notebook

**Comment by casperdcl** [comment]
just what we needed @lrq3000, thanks.
