### ISSUE TITLE
AttributeError: type object 'tqdm' has no attribute '_instances'

### ISSUE THREAD

**Issue by wernight** [tqdm/tqdm#188]
Running in Jupyter:

```
for index in tqdm.tnrange(10):
    tqdm.tqdm.write('test')
```

or just:

```
tqdm.tqdm.write('test')
```

Gives error:

```
/opt/conda/lib/python3.5/site-packages/tqdm/_tqdm.py in write(cls, s, file, end)
    309         # Clear all bars
    310         inst_cleared = []
--> 311         for inst in cls._instances:
    312             # Clear instance if in the target output file
    313             # or if write output + tqdm output are both either

AttributeError: type object 'tqdm' has no attribute '_instances'
```

**Comment by wernight** [comment]
Just using `print` work pretty well. May be a better error would be useful. I feel also often a bit confused with the short flat naming of various environments like `tnrange` vs `gnrange` vs `range`. May be a cleaner solution would be to have:

    # Do one of:
    import tqdm.console as tqdm
    import tqdm.gui as tqdm
    import tqdm.notebook as tqdm

    # All have same interface:
    tqdm.range(...)
    tqdm.tqdm(...)
    tqdm.write(...)

**Comment by lrq3000** [comment]
Hey Werner, thank's for your feedback :)

So you cannot use `tqdm` to write when you use `tnrange` (and thus `tqdm_notebook`) as your progress bar: there is one instance of a `tqdm_notebook` bar, but none of the parent `tqdm` bar, hence the message.

Hence, you should use the following:

```
from tqdm import tqdm_notebook, tnrange
for index in tnrange(10):
    tqdm_notebook.write('test')
```

It should work, but it doesn't anymore:

`AttributeError: 'function' object has no attribute 'write'`

This is because of a recent change (see #176) to delay the import of `tqdm_notebook` to avoid overloading memory and CPU unnecessarily. We will investigate how to fix that.

However, you can do the following:

```
from tqdm import tnrange

with tnrange(10) as t:
    for index in t:
        t.write('test')
```

This is totally equivalent and won't change in the API. Indeed, `tqdm.write()` can be used both as a class method, or as an instance method (thank's to Python flexibility!).

Tell me if this fixes your issue.

About your suggestion for `tqdm` architecture, I'll forward this over to #176, thank you :)

**Comment by casperdcl** [comment]
Hello, just checking - is this still an issue?

**Comment by casperdcl** [comment]
closing due to no further response. Will reopen if still an issue

**Comment by shashirawat29** [comment]
AttributeError: module 'notebook' has no attribute 'tqdm'
