### ISSUE TITLE
tqdm for C++?

### ISSUE THREAD

**Issue by CrazyPython** [tqdm/tqdm#221]
Perhaps a split project could be made doing what tqdm did to progress bars in Python to C++?

Use cases

 - Performance critical C++
 - CPU-bound programs

Attributes

 - Fast, like tqdm
 - Easy to use, like tqdm
 - Wrap around any iterable, like tqdm

**Comment by casperdcl** [comment]
yes, had a bit of code to this effect - guess I could add it to tqdm org...
one more item on long list of todo

**Comment by o11c** [comment]
I do a lot of C++, I could probably write that. Probably polish off and port my multicurl example too. Will initially target C++11 for `std::chrono` - callers usually want foreach anyway.

One thing I *would* like to see, especially for C++ (where performance is not terrible for trivial things like math and function calls), is throttling based on how much data we're writing to the TTY's buffer rather than based on a time limit. Since the only ultimate slowdown is displaying (for local TTYs with vsync - 60Hz is common) or sending over the network (for SSH - but probably *not* for mosh, which you really should be using anyway).

**Comment by CrazyPython** [comment]
@o11c @casperdcl initiative to start a tqdm c++ project under the tqdm originization name as an expiremental project. I don't mean that @casperdcl or @lrq3000 should write the code - just manage pull requests and collaborate on design issues.

**Comment by lrq3000** [comment]
Yes we can create a repo, if you have some draft ready we can setup the repo so that you can push there. We will be glad to accept any PR about this :)

@o11c about throttling based on TTY buffer limit, isn't it some kind of time limit after all? For example the 60Hz refresh rate corresponds to `mininterval=0.017`, which is a smaller time interval than the default 0.1 (so it's more expensive but more "realtime"). Do you suggest that we should see if it's possible to autodetect the refresh rate and set mininterval to this value?

**Comment by o11c** [comment]
It's not one *update* per 0.017 seconds, it's `PIPE_BUF` *bytes* per 0.017 seconds (or possibly even more if the master is read multiple times before the graphical calls start).

**Comment by CrazyPython** [comment]
@lrq3000 Let's make the repo first then the draft. It's hard to sketch something out without a repo  - it's good motivator.

I'm not so great at C++ - @o11c would you mind writing some boilerplate code for it, and possibly a draft?

**Comment by o11c** [comment]
I'll do some development in a fork once the placeholder repo exists.

**Comment by CrazyPython** [comment]
We're just waiting for the repo to be made, @casperdcl or @lrq3000. 
So, let's do it!

Let's target C++11 first, then later port it to C++98.
I want it to be super simple to install - like putting a single header file in sources root or something simple like that.

**Comment by lrq3000** [comment]
@casperdcl created the repo (https://github.com/tqdm/tqdm.cpp) this morning
and I just gave you both access to push there, please check your github
notifications and accept the permissions.

2016-08-09 16:14 GMT+02:00 CrazyPython <notifications@github.com>:
