### ISSUE TITLE
Code Climate

### ISSUE THREAD

**Issue by CrazyPython** [tqdm/tqdm#237]
Code Climate is a service that analyzes your git repo. It's easy to set up (enter repo name and wait - in fact it's already done). It builds automatically too. No configuration. So far, I've seen it give:
1. Cyclomactic complexity
2. Duplication warnings
3. Overall ratings
4. File ratings
5. Other statistics including quality over time
6. Badges

Right now, tqdm is at 0.96, pretty low for a project. test_pandas is pretty good, so whoever wrote that code, congrats!

Just wanted to let you guys know.

Link: https://codeclimate.com/github/tqdm/tqdm

**Comment by lrq3000** [comment]
I thought about using this kind of analysis for other projects (although not for tqdm), but I'm not sure it's a good idea here. The goal of these code quality analyses is to increase modularity and reduce complexity to reduce maintenance and increase code evolvability. The problem is that we are trying to have a very flexible API and to be super optimized at the same time, which contradicts somewhat some quality code precepts.

So it may be good to have this service running, but I don't think we should add a badge in the README nor try to meet all advices.

**Comment by casperdcl** [comment]
quite from https://codeclimate.com/github/tqdm/tqdm/tqdm/_tqdm.py:

```
Cyclomatic complexity is too high in method <strong>init</strong>. (27)
```
funny how their own formatting code is broken. Also, cyclomatic complexity? I think codacy (https://www.codacy.com/app/tqdm/tqdm/dashboard) has better issues and suggestions.
