### ISSUE TITLE
Add link to evolving tqdm.cpp project and wiki port list

### ISSUE THREAD

**Issue by CrazyPython** [tqdm/tqdm#243]
Useful for:
- Getting more devs for tqdm.cpp
- Less disappointed devs when there's a port in their favorite language.

**Comment by lrq3000** [comment]
Where would you like to add the link?

**Comment by CrazyPython** [comment]
@lrq3000 README + website. Forgot to include that.

**Comment by lrq3000** [comment]
Not now but when it matures enough I'm sure Casper will add it to the readme.

What website are you talking about?

**Comment by CrazyPython** [comment]
@lrq3000 

 - Add it now as a "Contribute to Pre-Alpha development of tqdm.cpp!". We need it when it's young so we can get devs. 
 - tqdm.github.io

**Comment by casperdcl** [comment]
I've never really been for the website, seeing as github landing pages automatically display the readme. Granted, it's hard with python repos because we're constrained by pypi-rst. Do either of you know how well pypi will cope with inline html and other such improvements? If we can get the readme looking better then we can just have the website auto redirect to github repo.

**Comment by CrazyPython** [comment]
@casperdcl Nope. But you can do a trick that makes it display on GitHub but not on PyPI.

**Comment by CrazyPython** [comment]
And I really think this should be higher priority, we need all the devs we can get for tqdm.cpp and possibly other ports.

**Comment by CrazyPython** [comment]
@casperdcl And a link works with the website and the README.

**Comment by lrq3000** [comment]
I don't think it's possible to feed html to pypi, it's probably sanity checked in order to avoid html and any malicious content that can go with it (at least I have never saw any project with html on their pypi page, but I have no idea about the warehouse, it might be possible on it).

EDIT: [HTML directives are not supported on PyPi.](https://stackoverflow.com/questions/8792817/embedding-html-in-restructured-text-on-pypi-package-pages)
