### ISSUE TITLE
`tqdm_notebook` for pandas

### ISSUE THREAD

**Issue by aplavin** [tqdm/tqdm#245]
As for now, `tqdm_notebook` doesn't seem to support `pandas` operations. Are there any issues which don't allow or complicate that?

**Comment by lrq3000** [comment]
Ah it doesn't work? Normally it should. Did you try it out (with the same usage as for core `tqdm`)?

**Comment by aplavin** [comment]
@lrq3000 there is no attribute `pandas` on `tqdm_notebook`, as opposed to `tqdm`.

Ah, now I see that `tqdm_notebook` is just a wrapper function, so the correct way is `tqdm_notebook().pandas()`. So, I guess it's just a documentation issue :)

**Comment by lrq3000** [comment]
Yes, that's the new usage case. But I disagree with `tqdm.pandas()` being a classmethod so it may get reverted to a decorator like before (`tqdm_pandas(tqdm_notebook())` instead of `tqdm_notebook().pandas()`).

**Comment by lrq3000** [comment]
Update on this: no it's not a documentation issue (or somewhat but let me explain) and you are right: to use `pandas()` with `tqdm_notebook` you need to do `tqdm_notebook().pandas()`. But to use it with core `tqdm` (or any other module) you just need to `tqdm.pandas()`.

So `tqdm_notebook` is the exception, because it has a delayer wrapper function to avoid automatic import when you import another module (because else it would import the whole `ipython notebook` suite and that's a huge slowdown, even if you just use core `tqdm`). Hence the non uniformized API.

For more info and a possible solution, see #198 (and please feedback to help us get forward!).

**Comment by lrq3000** [comment]
(Closing now because it's basically a duplicate and we need to reduce the number of issues, but it's still open in the linked PR! Don't hesitate to feedback there.)
