### ISSUE TITLE
Add non-iterator operating mode

### ISSUE THREAD

**Issue by flying-sheep** [tqdm/tqdm#25]
Some interfaces don’t work well with iterators, e.g.

> ##### [`urllib.request.urlretrieve(url, filename=None, reporthook=None, data=None)`](https://docs.python.org/3/library/urllib.request.html#urllib.request.urlretrieve)
> 
> […]
> The third argument, if present, is a hook function that will be called once on establishment of the network connection and once after each block read thereafter. The hook will be passed three arguments; a count of blocks transferred so far, a block size in bytes, and the total size of the file.
> […]

So for this to work we need a class that can be created with all but tqdm’s first argument, and has a `value` property, which on setting redraws the progress bar.

**Comment by hadim** [comment]
+1 see #24

**Comment by lrq3000** [comment]
My (now merged) PR should support this kind of usage (the file argument is optional so that update can be made manually by calling an .update() method), however maybe it could be nice to edit the tqdm class so that it can accept a callback_func optional argument, which if supplied would be called everytime tqdm is called so as to preprocess the given data?

For example with this urllib example, the dev using tqdm would not need to modify tqdm to correctly use the variables given by urllib, but define its own function which would receive all variables given to tqdm by urllib (or any other function) and then just return three things: the current n increase and total size. The idea is that it would work in a similar way to the callback for sorting and stuff like that.

**Comment by casperdcl** [comment]
I'd think you'd define your own reporthook function that is called by urllib and calls tqdm... Untested musings here, but something like:

```python
def my_hook(tsize=None):
    t = tqdm(total=tsize, unit='B', unit_scale=True)
    last_b = [0]
    def inner(b, bsize, tsize):
        t.total = tsize
        t.update((b - last_b[0]) * bsize)
        last_b[0] = b
    return inner
```

If I understood correctly. Not sure if a dynamically updating total would work due to necessary internal oop optimisations, though.

**Comment by casperdcl** [comment]
Edit: actually I think it will work, the optimisations only apply when using tqdm as a decorator/wrapper for an iterator, not for this kind of manual updating.

**Comment by casperdcl** [comment]
I'd also recommend `miniters=1` whenever there is potentially large differences in iteration speed (e.g. downloading a file over a patchy connection)

**Comment by lrq3000** [comment]
Ah ok I see, then it's useless to implement the callback management inside tqdm, that would actually be more complicated. Thank's for the code, I think it could be added to the readme as an example usage case, I'm sure OP and others with similar needs would find this very handy.

**Comment by lrq3000** [comment]
Ah and I also think that modifying the total on the fly should not be a problem, actually it happened on my setup sometimes due to some faulty initialization at some point and the progress bar is correctly redrawn without any issue (but of course this may change in the future depending on the code base).

**Comment by lrq3000** [comment]
Edit again (sorry): but having the possibility to change the total and redraw the bar may be necessary for some specific applications, for example if the total is but an estimation and it is reestimated on-the-fly as data is processed (eg, web resources?).

**Comment by casperdcl** [comment]
Yes, the total can change dynamically:

```python
t = tqdm()
for i in loop:
    ...
    t.total = new_total
    t.update(...)
```

However when wrapping an iterator it is assumed that the length of the iterator does not change: `t = tqdm(my_iterator)` assumes `len(my_iterator)` does not change. Manually calling `update()` for variable-length iterators I think is reasonable.

**Comment by casperdcl** [comment]
I've updated the `README` as per your request @lrq3000 . You're also an official author now :smile_cat:

**Comment by casperdcl** [comment]
Ok see #27 :+1:
