### ISSUE TITLE
Recommended recipe for using tqdm with compressed file?

### ISSUE THREAD

**Issue by reece** [tqdm/tqdm#274]
Is there a recommended recipe for using tqdm to iterate over a compressed file?

Conceptually, I'd like a drop-in replacement for `gzip.open()` that provides a progress bar based on file size. I am aware of the `update()` method and the wiki examples, but the compressed file case provides the additional challenges of supporting encoding (à la python 3's gzip.open).

Has anyone else been down this road already?

**Comment by lrq3000** [comment]
I did not work with gzip compressed files but I used `tqdm` with reed-solomon encoded files. The encoding of the processed files should not be an issue for `tqdm` because `tqdm` does not modify the content of the iterable, it only displays a bar in the console.

But IIRC, gzip does not provide the total length so you will have to first walk your archive to precompute `total` in a similar fashion to what is described here: https://github.com/tqdm/tqdm/wiki/How-to-make-a-great-Progress-Bar

If I did not understand correctly your issue, please provide more details and we will try to help :)

**Comment by reece** [comment]
I think there are two approaches. One is to use the compressed file size as `total`, then read and count compressed bytes, and pass to gzip (or zlib). The progress bar would be based on compressed data. 

Another way is to create a progress bar post-compression. For that, one would fetch the *un*compressed size, which is in the last 2 bytes of the file, and build a progress bar based on uncompressed content akin to the examples.

The challenge is to handle relevant cases of read modes (t,b) and encoding, and, ideally, to do this for Py2 and Py3.

So, thanks for tqdm and for responding. If there's no prescribed way no, you might consider parking this as a feature request for some contributor (maybe me, eventually) to take on. Again, thanks!

**Comment by casperdcl** [comment]
Please see #308 and [examples/7zx.py](https://raw.githubusercontent.com/tqdm/tqdm/master/examples/7zx.py) for an example of how to read zip metadata to figure out sizes before looping. Also feel free to reopen this issue if you feel the need (I'm closing it for now since there are a lot of other requests)
