### ISSUE TITLE
GUI?

### ISSUE THREAD

**Issue by casperdcl** [tqdm/tqdm#28]
Ok. This may be a really bad idea. But it must be said... GUI?

- add a default kwarg `gui=False`
- if `gui=True` attempt to use `matplotlib` animations
- can display rate graph for last 60 secs

Pros

- More end-user app friendly
- Windows users no longer get  terminated ( :wink:  ) by \r and \n
- Would have `numpy` so can try fitting different polynomials/regressions etc on rate to get better ETA
- GUIs are expected to be a bit slow anyway so enabling more features as above should be fine

Cons

- Will be slower even after optimisations. Probably will require `mininterval > 0.5`
- Could mess with other code that lazily relies on `gcf()`
- May not be a feature people are interested in?

**Comment by hadim** [comment]
I don't say it's a bad idea but I think it can be difficult to add a matplotlib backend in a clean way. But feel free to try it if you think it can be usefull to you and others.
I don't actively use tqdm anymore (I will in a few months) but the pretty thing I was thinking about sometime ago was to add an IPython widget backend that display a nice JS/CSS progress bar.

**Comment by casperdcl** [comment]
Hmm re: ipython, there's stuff like https://github.com/flying-sheep/smart-progress

**Comment by lrq3000** [comment]
Instead of making a standalone GUI for TQDM, maybe an integration with [Gooey](https://github.com/chriskiehl/Gooey) could be good? (making the GUI progress bar sync with TQDM). I think it would be more useful for most devs and users than a standalone GUI for TQDM, to me, a GUI progress bar is only useful when it's part of a GUI to configure the parameters of the app.

About ipython, TQDM is already compatible and works perfectly well, so there's no need to do anything (it should also work with the interactive widgets since the output is still piped from stdout).

**Comment by lrq3000** [comment]
Ah sorry Casper, I just saw you already made a branch with the GUI modification. Since you've done it, I think it can be a good addition, I'm sure some users can find it useful. The only tiny issue is that it adds quite a bit of complexity to the code. I saw you tried to modularize it, but do you think it's possible to separate the logic even more? I think that the more the GUI is separated logically, better it is to avoid any conflict with the base code (ie, if the GUI gets a flaw in the future, it won't affect the commandline progress bar).

**Comment by casperdcl** [comment]
Yeah the code duplication issue is similar to #9 but it seems necessary for speed optimisation... not an awfully long function so don't think it's too much of an issue... but if you can think of an elegant fix I'd be grateful...

**Comment by casperdcl** [comment]
Closed by pr #29
