### ISSUE TITLE
Modularize pyMakefile

### ISSUE THREAD

**Issue by lrq3000** [tqdm/tqdm#290]
`tqdm` implements in its `setup.py` a system simulating make and Makefiles in order to ease maintenance (running unit tests, building, uploading to pypi, etc.).

This system might interest other Python developers. Also, it isn't really related to `tqdm` per se, so I'm not sure it should be included inside the project.

Therefore, this system should be modularized into its own project `pyMakefile` (or another name?). The idea would be to monkeypatch distutils or setuptools, like setuptools does with distutils with a simple `import setuptools`. In the end, to enable `pyMakefile`, one should only prepend this in its own `setup.py`:

```
import distutils
import setuptools
import pymakefile
```

Then, `pyMakefile` will automatically monkeypatch distutils/setuptools to add the command `python setup.py make`.

Personal note, I think this project might have the potential of being eventually merged into the standard Python lib, if it gets enough traction by Python developers.

**Comment by casperdcl** [comment]
I seem to recall when designing our `Make` emulation that we integrated a few ideas from other projects. One of the objectives was for it to all be integrated so no dependencies. I don't think we should add `pymakefile` as a standalone dependency, though, even if it is pure-python. I made sure to not add `docopt` for CLI so that it could be "core" `tqdm` rather than an extension.

Still worth abstracting out makefile parsing into a separate repo just for teh world. Working on it.

**Comment by lrq3000** [comment]
Oh great Casper, I'm glad you like the idea, thank you for working on it :)

I don't remember that we have been inspired by any other project for our
pymakefile implementation. I remember there was a makefile that was
runnable only on Linux, and I wanted to be able to run it on Windows and
without any dependencies to make but only to python. I have looked other
implementations on the net but found notthing worth, so I just made a
simple finite state automata, and then you enhanced it to make a
beautifully useful plugin for tqdm :)

About dependencies, the idea is not to make pymakefile a necessary
dependency for tqdm, but rather an optional dependency for developers
wanting to build/unit-test tqdm.

Something like that in tqdm's setup.py:

```
try:
    import pymakefile
except ImportError:
    pass  # Or print a notice to tell user to install pymakefile to get
more build options
```

This way, tqdm could still be built without pymakefile (by just
copy/pasting the commands from the Makefile, which are just standard python
build commands in fact so the makefile is not even necessary), but if
pymakefile is installed then it would ease the builds by allowing for
aliases.

That's why I think it could also fit lots of other projects: it's really
just a bonus library that is only useful for developers, so it's both
optional but very useful when installed, it only adds features and never
implies a burden.

2016-10-28 20:55 GMT+02:00 Casper da Costa-Luis <notifications@github.com>:

**Comment by casperdcl** [comment]
cool. I've claimed `py-make` on pypi, since it's not allowing `pymake` (I don't know why since the latter deosn't exist). Check out the project at https://github.com/tqdm/pymake - it even has 80% coverage! xD.

Will close this issue here once
- [ ] first `py-make` binary release pushed to pypi
- [ ] `tqdm::setup.py` is updated as outlined above

**Comment by lrq3000** [comment]
Great work @casperdcl ! I'm reviewing the code today :)
