### ISSUE TITLE
asv-based performance tests

### ISSUE THREAD

**Issue by anntzer** [tqdm/tqdm#298]
Given the strong claims that asv makes regarding its performance, it may be relevant (or, from the point of view of the end user, more convincing) to use a tool such as asv (http://asv.readthedocs.io/en/latest/) to test the relevant timings.

**Comment by lrq3000** [comment]
Thank you @anntzer for making us aware of this lib, I didn't know it.

However, I'm not sure we can use it as part of our unit test, because asv tests seems to be machine dependent as it is an absolute time benchmark: it allows to track the evolution of runtime on the same machine over time, but it will differ if ran on another machine (eg, Travis, plus it has different overload rate over the course of the day), so I don't think we can automate it.

But it can be useful for us developers, combined with `examples/simple_examples.py` it can prove to be useful.

**Comment by lrq3000** [comment]
http://stackoverflow.com/questions/20503373/how-to-monkeypatch-pythons-datetime-datetime-now-with-py-test

**Comment by anntzer** [comment]
You don't actually have to be tracking absolute time, you can actually track arbitrary numerical values -- such as relative time (http://asv.readthedocs.io/en/latest/writing_benchmarks.html#tracking-generic).

**Comment by lrq3000** [comment]
Ok great! Thank you!

@casperdcl already implemented your suggestion, please feedback there in the discussion if you would like! (particularly about the incremental updating of results on different machines, I have no idea if this is possible).

**Comment by casperdcl** [comment]
merged in #301
