### ISSUE TITLE
Tracking process of decompression with tqdm

### ISSUE THREAD

**Issue by CrazyPython** [tqdm/tqdm#305]
Is this possible with the tqdm terminal command?

**Comment by lrq3000** [comment]
Theoretically you can track anything with tqdm commandline mode, but:

1. the piped app must provide a real-time output (verbose mode might be necessary).
2. to get a full bar with ETA prediction and not just the current state, the piped app must provide a total indication. Casper might answer more precisely here for the case of decompression, because I don't know how tqdm commandline can detect the total.

**Comment by casperdcl** [comment]
An initial naïve implementation (assuming numfiles >> file size variance):

``` sh
7z x -bd $ZIP_FILE | grep Extracting | \
  tqdm --unit files --total \
    $(7z l $ZIP_FILE | grep -Eo "[0-9]+ files" | cut -d' ' -f1) >> $ZIP_FILE.log
```

**Comment by casperdcl** [comment]
funny thing is I've just received a lot of large zip files so I might create a python script which handles this, taking into account individual file sizes.
