### ISSUE TITLE
`set_description` takes no effect until `.update()` is called

### ISSUE THREAD

**Issue by gwerbin** [tqdm/tqdm#317]
Expected behavior: `set_description()` takes effect immediately when called

Actual behavior: `set_description()` takes effect only when `.update()` is called.

Steps to reproduce

```python
import time

with tqdm(total=10, miniters=1, mininterval=0) as progress:
    for i in range(10):
        progress.set_description("step " + str(i + 1))
        time.sleep(0.5)
        progress.update()
```

Python version 3.5.2, TQDM version 4.10.0-10bd71

**Comment by lrq3000** [comment]
Hello @gwerbin,

You can use `progress.refresh()` to force the display refresh. Maybe we should force the refresh inside `set_description()`, we didn't give this much of a thought to be honest. The only thing is that `refresh()` is expensive because it then forces your bar display twice per iteration...

What you could rather do to be more computationally effective while having the same result would be to set the first iteration's description at tqdm initialization and move the call to `set_description()` to the end of the loop:

```
import time

with tqdm(total=10, miniters=1, mininterval=0, desc="step 0") as progress:
    for i in range(10):
        time.sleep(0.5)
        progress.set_description("step " + str(i + 1))
        progress.update()
```

**Comment by gwerbin** [comment]
@lrq3000 thanks, that makes sense. Maybe we can just call this a documentation issue then. There should be a "TQDM Cookbook" if there isn't already.

**Comment by ericfrederich** [comment]
I would consider this a bug.  Just add a call to `update()` or `refresh()` within `set_description()`.

It's interesting to note that the docs have this snippet of code:

```python
pbar = tqdm(["a", "b", "c", "d"])
for char in pbar:
    pbar.set_description("Processing %s" % char)
```

You'll never see "Processing a", so it should say *__"Processed"__* instead of *__"Processing"__*

**Comment by olalonde** [comment]
This seems like a bug.. `.refresh()` doesn't fix the issue here.

**Comment by ChrisPVille** [comment]
I've also run into this issue.  I've moved the progress bar into its own worker thread, and I still can't seem to get the postfix to update with `.refresh()` or `.update(0)`.  It usually does draw correctly after `.update(1)` or larger, but this obviously skews the results upward.

**Comment by ericfrederich** [comment]
Thanks @casperdcl ... I was surprised to see how far back this issue went.  I agree though, perhaps refresh should be set to `False`
