### ISSUE TITLE
tqdm_notebook and tqdm.pandas fails when given *total* argument.

### ISSUE THREAD

**Issue by karhohs** [tqdm/tqdm#364]
My code:

>import tqdm
df = pandas dataframe with 1000 rows
tqdm.tqdm_notebook().pandas(total="1000")
df.progress_apply(myfunction, axis=1)

The error:

>C:\pythonstuff\lib\site-packages\tqdm\_tqdm.py in inner(df, func, *args, **kwargs)
    511                     deprecated_t[0] = None
    512                 else:
--> 513                     t = tclass(*targs, total=total, **tkwargs)
    514 
    515                 # Define bar updating wrapper
TypeError: type object got multiple values for keyword argument 'total'

Without specifying *total* it seems to work, but I don't get a percentage from the output. Also there is an extra bar.

![tqdm_notebook_pandas](https://cloud.githubusercontent.com/assets/156232/24570067/903e5906-1637-11e7-82b9-e794752a32b3.gif)

**Comment by DevJac** [comment]
This happens with `tqdm.tqdm.pandas` as well. The issue seems to be that tqdm assumes the total count is the number of pandas columns, but `df.progress_apply(myfunction, axis=1)` is applying `myfunction` to *rows*, not *columns*.

If you attempt to manually specify the total, tqdm throws and exception because it "got multiple values for keyword argument 'total'". And if you don't manually specify a total, tqdm uses the *columns count* rather than the *row count*.

As a workaround, the deprecated `tqdm_pandas(tqdm(total=df.shape[0]))` way of doing things is working for me.

**Comment by chengs** [comment]
This is confirmed. Try to solve it.

**Comment by casperdcl** [comment]
yes, this is easy to solve, surprised I didn't do it already.

**Comment by chengs** [comment]
@casperdcl I am working on it. I will write a unit test

**Comment by casperdcl** [comment]
related: #530, #535

**Comment by chengs** [comment]
@casperdcl yep, maybe merge 8b0bdc6, #530, #535 together
