### ISSUE TITLE
Type issue with numpy.ndenumerate

### ISSUE THREAD

**Issue by ManyAngledOne** [tqdm/tqdm#402]
The code:
```
import tqdm
import numpy as np
slopes = np.linspace(2.5e8, 3.1e8, 101)
for i, s in np.ndenumerate(tqdm.tqdm(slopes)):
    s/2
```
Gives me:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-14-07dca8068b6c> in <module>()
      1 slopes = np.linspace(2.5e8, 3.1e8, 101)
      2 for i,s in np.ndenumerate(tqdm.tqdm(slopes)):
----> 3     s/2
TypeError: unsupported operand type(s) for /: 'tqdm' and 'int'
```
What am I doing wrong?
Thanks.

**Comment by chengs** [comment]
I think this usage is wrong, because what np.ndenumerate receives is np.ndarray (https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.ndenumerate.html). 
So, the tqdm warp should be outside, like what @casperdcl suggests. 
```
tqdm.tqdm(np.ndenumerate(slopes), total=len(slopes))
```

I check the code of **np.ndenumerate**, it converts the input to np.ndarray using **np.core.numeric.asarray(input)**, which only recevies lists, lists of tuples, tuples, tuples of tuples, tuples of lists and ndarrays.

**Comment by casperdcl** [comment]
thanks @chengs
