### ISSUE TITLE
Travis py2.6

### ISSUE THREAD

**Issue by casperdcl** [tqdm/tqdm#411]
Don't really have time to look into this but Travis py2.6 hasn't been working for ages.

see [comment](https://github.com/tqdm/tqdm/pull/409#issuecomment-315561609) in #409 (and also [all recent travis builds](https://travis-ci.org/tqdm/tqdm/builds))

@hugovk I've noticed you on [travis-ci/travis-ci#2219](https://github.com/travis-ci/travis-ci/issues/2219), any ideas what we need to change in our config to get travis to work with py2.6 again?

**Comment by hugovk** [comment]
It's failing already when trying to set up the environment with tox. I'm not so familiar with tox, but I would recommend dropping support for Python 2.6 as it CPython 2.6 itself has not been supported since 2013 and many other libraries and tools, notably pip and coverage, no longer support it either. So it will be a struggle to get it green even after sorting tox out. 

https://en.wikipedia.org/wiki/CPython#Version_history
