### ISSUE TITLE
magic tqdm

### ISSUE THREAD

**Issue by KOLANICH** [tqdm/tqdm#443]
```python
from isNotebook import isNotebook
from tqdm import *

"""Magic calling needed tqdm depending on environment"""

if isNotebook():
	mtqdm=tqdm_notebook
else:
	mtqdm=tqdm
```
where ```isNotebook``` is according to https://stackoverflow.com/questions/15411967/how-can-i-check-if-code-is-executed-in-the-ipython-notebook/39662359#39662359

**Comment by KOLANICH** [comment]
@casperdcl

**Comment by casperdcl** [comment]
This is nice but has the additional `isNotebook` dependency. Might be better to add to the documentation rather than to the library

**Comment by KOLANICH** [comment]
We have to reimplement IsNotebook. It's pretty tiny.

**Comment by casperdcl** [comment]
yes but my concern is there doesn't seem to be a consensus on how precisely to write an `isNotebook` that actually works in all cases

**Comment by KOLANICH** [comment]
That one works very well, as intended. At least in my case.

**Comment by joshbode** [comment]
I've been using the following in my library, where I only want the progress bars if I'm running in an interactive environment:
```
if 'IPython' in sys.modules:

    from IPython import get_ipython

    if 'IPKernelApp' in get_ipython().config:
        from tqdm import tqdm_notebook as tqdm
    else:
        from tqdm import tqdm

else:

    def tqdm(x, **kwargs):
        """Fake progress function."""

        return x
```

**Comment by joshbode** [comment]
something like this could possibly work, which correctly returns `False` for `ipython`, `jupyter console` and `jupyter qtconsole`:
```
import re
import psutil

def is_notebook():
    return any(re.search(r'\bjupyter-(lab|notebook)\b', x) for x in psutil.Process().parent().cmdline())
```

**Comment by chengs** [comment]
maybe checking ipywidget instead of jupyter?

**Comment by casperdcl** [comment]
Basically, we can detect:

1. `ipython`/`python`
2. `jupyter console`/`notebook`

the problem being that `console` is not distinguishable from `notebook` by design:

- https://stackoverflow.com/questions/34091701/determine-if-were-in-an-ipython-notebook-session
- https://stackoverflow.com/questions/15411967/how-can-i-check-if-code-is-executed-in-the-ipython-notebook

I'd be in favour of:

```python
from tqdm.magic import tqdm
```

which would:

- if in plain terminal/ipython: return `tqdm`
- if in jupyter, actually return `tqdm_notebook` but warn that `jupyter console` won't work properly

**Comment by KOLANICH** [comment]
🎉
