### ISSUE TITLE
Move progress bar back to a value? 

### ISSUE THREAD

**Issue by markddavidoff** [tqdm/tqdm#545]
If i want to set the progress bar to a specific point, update only allows postive values, so how do i do that?

**Comment by chengs** [comment]
just set n manually and then update. See #374 
```python
from tqdm import tqdm
from time import sleep
pbar = tqdm(range(100))
pbar.update(50)
pbar.refresh()
sleep(2)
pbar.n = 10 #check this
pbar.refresh() #check this
sleep(2)
pbar.update(30)
```

**Comment by chengs** [comment]
@casperdcl how about we add this into Faq of README and close #545, #432, #374?

**Comment by grollinger** [comment]
After resetting `n`, the progress bar might not update automatically, any more (see also #547).

I've found that what helps resolve that is to also reset `last_print_n`

```python
pbar.n = 10 
pbar.last_print_n = 10 
```

**Comment by casperdcl** [comment]
Somewhat messes with ETA and the concept of a progressbar - sounds more like a meter (for e.g. monitoring CPU usage)

**Comment by grollinger** [comment]
> Somewhat messes with ETA and the concept of a progressbar - sounds more like a meter (for e.g. monitoring CPU usage)

Indeed.

For the moment I'm also resetting the start time and last_print_time.

And all that because I have to reuse a single progress bar for multiple tasks.
Otherwise I'd have an ever growing whitespace in the notebook output section (#479 ).

**Comment by casperdcl** [comment]
I believe you may want to use ```
with tdqm(...) as t:
  ...
  t.unpause()
```

**Comment by grollinger** [comment]
If I understand correctly what `unpause()` does, that would mean that the total time keeps accumulating across tasks which I don't want to happen.

**Comment by flutefreak7** [comment]
> > Somewhat messes with ETA and the concept of a progressbar - sounds more like a meter (for e.g. monitoring CPU usage)
> 
> Indeed.
> 
> For the moment I'm also resetting the start time and last_print_time.
> 
> And all that because I have to reuse a single progress bar for multiple tasks in my Jupyter notebook.
> Otherwise I'd have an ever growing whitespace in the output section (#479).

I'm trying to do something similar to @grollinger.  Is this equivalent to what you are doing to "reset" a progressbar for reuse on another task?  

```python
pbar.n = 0
pbar.last_print_n = 0
pbar.start_t = time()
pbar.last_print_t = time()
pbar.update()
```

It really makes sense that the progress bar should be capable of resetting... like if a task is cancelled and restarted for any reason. That's how a download meter in a web browser works if I cancel and restart a download.  The desire to reset or backtrack doesn't mean its a "meter" like a CPU meter, it just means the concept of task "progress" is not always monotonically increasing.  I understand that messes with completion estimation, which is why the simplest scenario is to support a full reset and then later address how to handle back tracking.
