### ISSUE TITLE
tqdm.pandas() ImportError: cannot import 'PanelGroupBy'

### ISSUE THREAD

**Issue by aaronkollasch** [tqdm/tqdm#555]
When using tqdm v4.23.3 and pandas v0.23.0, I get this error:

```
>>> from tqdm import tqdm
>>> tqdm.pandas()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/username/.conda/envs/py36/lib/python3.6/site-packages/tqdm/_tqdm.py", line 545, in pandas
    from pandas.core.groupby import PanelGroupBy
ImportError: cannot import name 'PanelGroupBy'
```
It looks like pandas has moved GroupBy to a submodule, and PanelGroupBy is not included in [pandas/core/groupby/\_\_init\_\_.py](https://github.com/pandas-dev/pandas/blob/v0.23.0/pandas/core/groupby/__init__.py), though it remains in [pandas/core/groupby/groupby.py](https://github.com/pandas-dev/pandas/blob/v0.23.0/pandas/core/groupby/groupby.py).

Thus, for the latest version of pandas, PanelGroupBy can only be imported using `from pandas.core.groupby.groupby import  PanelGroupBy`.

I've reverted to the previous version of pandas and that fixed the problem, so this is a heads up for the newest and future pandas versions.

**Comment by andrewnc** [comment]
What is the status on this fix?

**Comment by casperdcl** [comment]
should be fixed in `tqdm>=4.23.4`

**Comment by will-holley** [comment]
I am getting this issue in `4.32.2`

**Comment by casperdcl** [comment]
yes, as per #780 this is now due to `pandas==0.25.0` on `python3`

**Comment by will-holley** [comment]
I saw that after posting; thanks for following up, @casperdcl.

**Comment by casperdcl** [comment]
just in case someone else winds up here to follow the trail :)

**Comment by chwonghk01** [comment]
Got the same error with `pandas==0.25.0` and `tqdm==4.32.2`, downgrade to `pandas==0.24.0` works.

**Comment by aloosley** [comment]
At the time of writing this comment, one does not need to downgrade pandas from `pandas==0.25.0` but rather update tqdm.  I updated tqdm today to `tqdm==4.36.1` and everything works.

**Comment by casperdcl** [comment]
yes as per https://github.com/tqdm/tqdm/issues/780#issuecomment-519589160 fixed in `tqdm>=4.33.0`

**Comment by casperdcl** [comment]
likely to break again at some time in future since

1. `pandas` has an unstable API
2. I don't use `pandas`

**Comment by lapolonio** [comment]
I think this broke again with pandas 1.0.0

**Comment by casperdcl** [comment]
v1.0.0? Awesome! Major version 1 means it's unlikely to break again once it's re-fixed.

**Comment by JayBits** [comment]
Unsure what i am doing wrong but getting the same error even after upgrading.

pandas.__version__  : 1.0.1
tqdm.__version__ : 4.43.0

**Comment by sakshamjn** [comment]
Hey 
I think this problem comes again in tqdm version 4.43.0

**Comment by Hadrien-Cornier** [comment]
I have 
Python 3.6.9
tqdm 4.28.1
pandas 0.25.3

And I have the error message : 

`---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/tqdm/_tqdm.py in pandas(tclass, *targs, **tkwargs)

ImportError: cannot import name 'DataFrameGroupBy'`

**Comment by Hadrien-Cornier** [comment]
Nevermind, I just needed to upgrade to ```tdqm==4.43.0``` and it fixed it !

**Comment by chunfengh** [comment]
I think this problem still exist with following:
 
Pandas vesion: 1.1.5
Python version: 3.6.13
tqdm version: v4.61.1

ImportError: cannot import name 'PanelGroupBy'

If the module is lightweight, try adhoc_import - http://go/adhoc-import
If you're already using adhoc_import and are having trouble, see http://go/adhoc-trouble.
Otherwise, use a custom runtime - http://go/colab-custom-runtime
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
tqdm/_tqdm.py in pandas(tclass, *targs, **tkwargs)
    593             # pandas>=0.23.0
--> 594             from pandas.core.groupby.groupby import DataFrameGroupBy, \
    595                 SeriesGroupBy, GroupBy, PanelGroupBy

ImportError: cannot import name 'DataFrameGroupBy'

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
1 frames
<ipython-input-15-aa3b5d28091d> in <module>()
      7 from tqdm import tqdm
      8 
----> 9 tqdm.pandas()
     10 
     11 RESULT_ENTRY_COL = 'COLUMN'

tqdm/_tqdm.py in pandas(tclass, *targs, **tkwargs)
    595                 SeriesGroupBy, GroupBy, PanelGroupBy
    596         except ImportError:
--> 597             from pandas.core.groupby import DataFrameGroupBy, \
    598                 SeriesGroupBy, GroupBy, PanelGroupBy
    599 

ImportError: cannot import name 'PanelGroupBy'

**Comment by casperdcl** [comment]
@chunfengh you're definitely not using `tqdm==4.61.1`, you're using `tqdm<=4.35.0`
