### ISSUE TITLE
README lost in translation

### ISSUE THREAD

**Issue by pedromartins4** [tqdm/tqdm#577]
Where the introduction page reads:

```
... and an abbreviation for "I love you so much" in Spanish (te quiero demasiado) ...
```

it should actually read "I love you too much". "Demasiado" in Spanish or Portuguese directly translates to "too", meaning something to a higher degree that is desirable, whereas "so" means something to a great extent without it being in excess:

``` I am being so pedantic right now I can't even... ```

**Comment by casperdcl** [comment]
Having checked with Spanish speakers (e.g. @mabelzunce), I think [*demasiado*](https://translate.google.com/#es/en/demasiado) does indeed imply excess (*too*), but due to English nuances the phrase as  a whole is more appropriately translated using *so* rather than *too*. The former implies excess in this context, while the latter just doesn't sound right. I'm tempted to stick with the current version, favouring [transparency over fidelity](https://en.wikipedia.org/wiki/Translation#Fidelity_and_transparency) ([dynamism over formalism](https://en.wikipedia.org/wiki/Dynamic_and_formal_equivalence)).

Translator's dilemma:
[1] http://www.translationdirectory.com/article99.htm
[2] https://manifoldgreatness.wordpress.com/2013/05/09/the-translators-dilemma-or-how-do-you-say-that-in-english/

`I so referenced I can't even :P`

**Comment by pedromartins4** [comment]
Haha.
I agree, `so much` does sounds better and more natural, although Human League does [sing](https://www.youtube.com/watch?v=zO0Rymfm2ys):
```
AAahhhhhh
I love you too much
I love you too much
```
maybe it's because they are British, maybe I'm being _too_ pedantic.

**Comment by casperdcl** [comment]
closing this because there are >100 open issues. keep up the love, though!

**Comment by 0x2b3bfa0** [comment]
**See also**

* https://dle.rae.es/demasiado
* https://www.udep.edu.pe/hoy/2013/01/te-quiero-demasiado
