### ISSUE TITLE
Maybe set the default repository branch to devel instead of master

### ISSUE THREAD

**Issue by altendky** [tqdm/tqdm#675]
Maybe set the default repository branch to devel instead of master

**Comment by casperdcl** [comment]
I understand why this would be useful for devs/contribs, but unfortunately it would potentially

1. affect the primary documentation page https://github.com/tqdm/tqdm/
2. confuse some people and automation tools into using/treating `devel` as stable

**Comment by altendky** [comment]
1. Ok, though that seems like an indication that released documentation should be located elsewhere.
2. Why are people that want something stable using an unspecified branch from a repository?

**Comment by altendky** [comment]
1. Actually, why are people that want released documentation going to a repository?  The released docs are already on PyPI where released stuff goes, right?

**Comment by casperdcl** [comment]
1. Well the nice thing about https://github.com/tqdm/tqdm is it contains links to everything (wiki, issues, history, etc). If we want to change to something else, we'd have to update the documentation everywhere to say so. I'd suggest https://tqdm.github.io rather than https://pypi.org/project/tqdm
2. Can't assume people at large do what we want them to

**Comment by altendky** [comment]
2. Can't design your development process around what everyone might do :]

Anyways, I figure your decision is to leave it as is.  Probably not much more to discuss.
