### ISSUE TITLE
Resume progress, add start offset

### ISSUE THREAD

**Issue by munro** [tqdm/tqdm#70]
When resuming a job, it would be nice if we could display that to the user, without simply quickly skipping a bunch of iterations.  Which would throw off the ETA, as well as wouldn't show visual feedback to the user that their job has been resumed.

I propose adding a `start` offset, which will just offset the existing `total` & starting position of the iterator passed in.

So if you pass in an total of 10, it would look like this.

```
0% [    ] 0/10 [....]
```

Then adding `start=10` will offset the starting index, and total, like this:

```
50% [----    ] 10/20 [....]
```

The resume part of the bar should look different, not sure how exactly, maybe just a different pattern or darker color.  Here's wget for inspiration.

![image](https://cloud.githubusercontent.com/assets/500774/11982473/5990e30a-a960-11e5-8052-8bc965eec135.png)

**Comment by lrq3000** [comment]
Good idea but that's a bit tricky, because the ETA is recomputed online, there's no memorization. However, the ETA smoothing should correct the throw off after a few iterations.

I'll see if we can find an elegant way to implement what you want. About showing the resumed part in a different look, I'm not sure we will do that, because this will make the status printing more complicated (we have ascii and unicode console bars, and then we have ipython, gui, etc. so this means setting a different "resume character" for each of these cases).

**Comment by casperdcl** [comment]
Start offset fixed by #74

**Comment by casperdcl** [comment]
resume fixed by #86
