### ISSUE TITLE
I think the project name should be changed

### ISSUE THREAD

**Issue by junknet** [tqdm/tqdm#995]
I think we should use a meaningful English name, because I always forget this name

**Comment by t-mart** [comment]
FWIW, I recently did `pip install tdqm`. Fortunately, that package does exist (yet). [I went to PyPI to confirm soon after](https://pypi.org/search/?q=tdqm).

https://en.wikipedia.org/wiki/Typosquatting
https://arxiv.org/abs/2003.03471

Not sure if this is a common typo, but with a package name that doesn't reference a common word/acronym/etc, no red flag came up in my mind when typing that command out.

Instead of considering a name change, I'd first consider parking that package name.

**Comment by casperdcl** [comment]
@t-mart 

Seen that before; https://github.com/tqdm/tqdm/issues/429...

Just created https://github.com/tqdm/tdqm-typo and https://pypi.org/project/tdqm/ :)

Regarding changing project name; `tqdm` gets millions of downloads a week and there are lots of :-1: on this issue so it looks like Earth doesn't want change.
